name: "Continuous Integration"

on: [push, pull_request]

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  SYMFONY_PHPUNIT_VERSION: "8.5"

jobs:
  tests:
    name: "CI"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        composer-version: ["v1"]
        phpdotenv-version: ["^4.0"]
        include:
          - php-version: "7.4"
            composer-version: "v1"
            phpdotenv-version: "^4.0"
          - php-version: "7.4"
            composer-version: "v1"
            phpdotenv-version: "^5.0"
          - php-version: "7.4"
            composer-version: "snapshot"
            phpdotenv-version: "^4.0"
          - php-version: "7.4"
            composer-version: "snapshot"
            phpdotenv-version: "^5.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Choose PHPUnit version"
        run: |
          if [ "${{ matrix.php-version }}" = "7.1" ]; then
            echo "SYMFONY_PHPUNIT_VERSION=7.5" >> $GITHUB_ENV;
          else
            echo "SYMFONY_PHPUNIT_VERSION=8.5" >> $GITHUB_ENV;
          fi

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0"
          php-version: "${{ matrix.php-version }}"
          tools: "composer:${{ matrix.composer-version }}"

      - name: "Install dependencies using composer"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Switch to specified vlucas/phpdotenv version"
        run: "composer require vlucas/phpdotenv:${{ matrix.phpdotenv-version }} ${{ env.COMPOSER_FLAGS }}"

      - name: "Run test suite"
        run: "composer test"
