name: "Continuous Integration"

on:
  push:
  pull_request:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  SYMFONY_PHPUNIT_VERSION: "8.5"

jobs:
  tests:
    name: "CI"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        php-version:
          - "5.6"
          - "7.4"
        dependencies: [locked]
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - php-version: "5.6"
            composer-version: "v1"
            os: ubuntu-latest
            experimental: false
          - php-version: "5.6"
            composer-version: "v2"
            os: ubuntu-latest
            experimental: false
          - php-version: "7.4"
            composer-version: "v1"
            os: ubuntu-latest
            experimental: false
          - php-version: "7.4"
            composer-version: "v2"
            os: ubuntu-latest
            experimental: false

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Choose PHPUnit version"
        run: |
          if [ "${{ matrix.php-version }}" = "5.6" ]; then
            echo "SYMFONY_PHPUNIT_VERSION=5.7" >> $GITHUB_ENV;
          else
            echo "SYMFONY_PHPUNIT_VERSION=8.5" >> $GITHUB_ENV;
          fi

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0"
          php-version: "${{ matrix.php-version }}"
          tools: "composer:${{ matrix.composer-version }}"

      - name: "Install dependencies using composer"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Run test suite"
        run: "composer test"
